"use strict";
(function(){
  const q=new URLSearchParams(location.search); const allowed=["cafe","warung","retail"]; let mode=allowed.includes(q.get("mode"))?q.get("mode"):"cafe";
  const META={cafe:{icon:"☕",name:"Kafe",desc:"Menu visual · Soft Stock · navigasi ringkas"},warung:{icon:"🍜",name:"Warung",desc:"Barang & menu praktis · Soft Stock"},retail:{icon:"🛒",name:"Toko Ritel",desc:"Barcode · Strict Stock · inventori lengkap"}};
  const nav={cafe:[["dashboard.html","📊 Dashboard"],["kasir.html","💵 Kasir"],["barang.html","☕ Menu & Produk"],["operasional.html","🧺 Bahan & Pembelian"],["laporan.html","📑 Laporan"],["multi-store.html","⇄ Cabang"]],warung:[["dashboard.html","📊 Dashboard"],["kasir.html","💵 Kasir"],["barang.html","🍜 Barang & Menu"],["operasional.html","🧺 Belanja & Supplier"],["laporan.html","📑 Laporan"]],retail:[["dashboard.html","📊 Dashboard"],["kasir.html","💵 Kasir"],["barang.html","📦 Barang & Stok"],["laporan.html","📑 Laporan"],["operasional.html","⚙️ Operasional"],["multi-store.html","⇄ Multi-Store"]]};
  const catalog={cafe:[{n:"Es Kopi Susu",p:18000,pic:"☕",stock:0},{n:"Matcha Latte",p:20000,pic:"🍵",stock:2},{n:"Croissant",p:16000,pic:"🥐",stock:4}],warung:[{n:"Nasi Goreng",p:15000,pic:"🍚",stock:0},{n:"Es Teh",p:5000,pic:"🧋",stock:3},{n:"Indomie",p:10000,pic:"🍜",stock:1}],retail:[{n:"Aqua 600ml",p:3500,stock:0},{n:"Indomie Goreng",p:3200,stock:2},{n:"Susu UHT",p:7500,stock:8},{n:"Beras 5 Kg",p:78000,stock:3}]};
  function money(v){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v)}
  function href(file){return `${file}?mode=${encodeURIComponent(mode)}`}
  function initShell(){document.body.classList.add(`mode-${mode}`); const ms=document.querySelector("#demoMode"); if(ms){ms.value=mode;ms.onchange=()=>{location.href=`${location.pathname.split('/').pop()}?mode=${encodeURIComponent(ms.value)}`}} const n=document.querySelector("#demoNav"); if(n){const current=location.pathname.split('/').pop();n.innerHTML=nav[mode].map(([f,l])=>`<a class="${f===current?'active':''}" href="${href(f)}">${l}</a>`).join("")} document.querySelectorAll("[data-mode-title]").forEach(e=>e.textContent=`${META[mode].icon} ${META[mode].name}`);document.querySelectorAll("[data-mode-desc]").forEach(e=>e.textContent=META[mode].desc)}
  function dateKey(d){const x=new Date(d);const p=n=>String(n).padStart(2,"0");return `${x.getFullYear()}-${p(x.getMonth()+1)}-${p(x.getDate())}`}
  function day(off){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+off);return dateKey(d)}
  function samples(){return [{id:"D-001",date:day(0),cashier:"Kasir Demo",total:52000,method:"Tunai"},{id:"D-002",date:day(0),cashier:"Kasir Demo",total:28500,method:"QRIS"},{id:"D-003",date:day(-1),cashier:"Kasir Demo",total:87000,method:"Tunai"},{id:"D-004",date:day(-1),cashier:"Kasir Demo",total:33000,method:"QRIS"},{id:"D-005",date:day(-2),cashier:"Kasir Demo",total:115000,method:"Tunai"},{id:"D-006",date:day(-6),cashier:"Kasir Demo",total:64000,method:"Tunai"}]}
  window.LDMDemo={mode,META,catalog,money,href,initShell,day,dateKey,samples};
})();
